# memoise functions to avoid redundant computation of the current selection
# and selection helpers

current_call                 <- memoise::memoise(current_call)
current_code_block           <- memoise::memoise(current_code_block)
current_env                  <- memoise::memoise(current_env)
current_expr                 <- memoise::memoise(current_expr)
current_file_code            <- memoise::memoise(current_file_code)
current_file_is_r_script     <- memoise::memoise(current_file_is_r_script)
current_file_is_rmd          <- memoise::memoise(current_file_is_rmd)
current_line_numbers         <- memoise::memoise(current_line_numbers)
current_lines                <- memoise::memoise(current_lines)
current_path                 <- memoise::memoise(current_path)
current_selection            <- memoise::memoise(current_selection)
current_value                <- memoise::memoise(current_value)
selection_is_call            <- memoise::memoise(selection_is_call)
selection_is_comment_block   <- memoise::memoise(selection_is_comment_block)
selection_is_comment_line    <- memoise::memoise(selection_is_comment_line)
selection_is_empty           <- memoise::memoise(selection_is_empty)
selection_is_evaluable       <- memoise::memoise(selection_is_evaluable)
selection_is_litteral        <- memoise::memoise(selection_is_litteral)
selection_is_litteral_number <- memoise::memoise(selection_is_litteral_number)
selection_is_litteral_string <- memoise::memoise(selection_is_litteral_string)
selection_is_n_lines         <- memoise::memoise(selection_is_n_lines)
selection_is_parsable        <- memoise::memoise(selection_is_parsable)
selection_is_reserved_word   <- memoise::memoise(selection_is_reserved_word)
selection_is_simple_call     <- memoise::memoise(selection_is_simple_call)
selection_is_single_line     <- memoise::memoise(selection_is_single_line)
selection_is_symbol          <- memoise::memoise(selection_is_symbol)

# relevant_funs <- Filter(
#   function(x) startsWith(x, "current_") || startsWith(x, "selection_is"),
#   ls(asNamespace("poof")))
# cat(paste0(relevant_funs, " <- memoise::memoise(", relevant_funs, ")", collapse = "\n"))
# cat(paste0("memoise::forget(", relevant_funs, ")", collapse = "\n"))


forget_all <- function() {
  memoise::forget(current_call)
  memoise::forget(current_code_block)
  memoise::forget(current_env)
  memoise::forget(current_expr)
  memoise::forget(current_file_code)
  memoise::forget(current_file_is_r_script)
  memoise::forget(current_file_is_rmd)
  memoise::forget(current_line_numbers)
  memoise::forget(current_lines)
  memoise::forget(current_path)
  memoise::forget(current_selection)
  memoise::forget(current_value)
  memoise::forget(selection_is_call)
  memoise::forget(selection_is_comment_block)
  memoise::forget(selection_is_comment_line)
  memoise::forget(selection_is_empty)
  memoise::forget(selection_is_evaluable)
  memoise::forget(selection_is_litteral)
  memoise::forget(selection_is_litteral_number)
  memoise::forget(selection_is_litteral_string)
  memoise::forget(selection_is_n_lines)
  memoise::forget(selection_is_parsable)
  memoise::forget(selection_is_reserved_word)
  memoise::forget(selection_is_simple_call)
  memoise::forget(selection_is_single_line)
  memoise::forget(selection_is_symbol)
}
